In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
print(" Starting my ML journey today!")
print(f"NumPy version: {np.__version__}")

 Starting my ML journey today!
NumPy version: 2.0.2


In [4]:
print("\n=== Exercise 1: Random Matrix ===")
matrix = np.random.rand(3, 3)
print("Random 3x3 matrix:")
print(matrix)


=== Exercise 1: Random Matrix ===
Random 3x3 matrix:
[[0.93890558 0.04010457 0.07458091]
 [0.8230828  0.70747452 0.49449308]
 [0.68102081 0.62954155 0.202501  ]]


In [5]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-2iyom4cp/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-2iyom4cp/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-2iyom4cp/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-2iyom4cp/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64B

In [6]:
print(f"\nMax value: {matrix.max():.4f}")
print(f"Min value: {matrix.min():.4f}")
print(f"Mean value: {matrix.mean():.4f}")
print(f"Standard deviation: {matrix.std():.4f}")


Max value: 0.9389
Min value: 0.0401
Mean value: 0.5102
Standard deviation: 0.3109


In [7]:
print("\n=== Exercise 3: Reshaping ===")
flat_array = matrix.reshape(-1)
print(f"Original shape: {matrix.shape}")
print(f"Flattened shape: {flat_array.shape}")
print(f"Flattened array: {flat_array}")


=== Exercise 3: Reshaping ===
Original shape: (3, 3)
Flattened shape: (9,)
Flattened array: [0.93890558 0.04010457 0.07458091 0.8230828  0.70747452 0.49449308
 0.68102081 0.62954155 0.202501  ]


In [8]:
print("\n=== Exercise 4: Element-wise Operations ===")
squared = matrix ** 2
print("Matrix squared:")
print(squared)


=== Exercise 4: Element-wise Operations ===
Matrix squared:
[[0.88154368 0.00160838 0.00556231]
 [0.6774653  0.50052019 0.2445234 ]
 [0.46378934 0.39632257 0.04100666]]


In [9]:
print("Matrix * 2 + 1:")
print(matrix * 2 + 1)

Matrix * 2 + 1:
[[2.87781116 1.08020914 1.14916182]
 [2.64616561 2.41494903 1.98898615]
 [2.36204162 2.25908311 1.405002  ]]


In [10]:
print("\n=== Exercise 5: Boolean Indexing ===")
condition = matrix > 0.5
print(f"Number of values > 0.5: {np.sum(condition)}")
print("Values greater than 0.5:")
print(matrix[condition])


=== Exercise 5: Boolean Indexing ===
Number of values > 0.5: 5
Values greater than 0.5:
[0.93890558 0.8230828  0.70747452 0.68102081 0.62954155]


In [11]:
print("=== Exercise 6: Matrix Operations ===")
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(matrix_a)
print("Matrix B:")  
print(matrix_b)

=== Exercise 6: Matrix Operations ===
Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]


In [12]:
dot_product = np.dot(matrix_a, matrix_b)
print("A @ B (dot product):")
print(dot_product)

# Element-wise multiplication
element_wise = matrix_a * matrix_b
print("A * B (element-wise):")
print(element_wise)


A @ B (dot product):
[[19 22]
 [43 50]]
A * B (element-wise):
[[ 5 12]
 [21 32]]


In [13]:
print("\n=== Exercise 7: Linear Algebra ===")
# Eigenvalues and eigenvectors
eigenvals, eigenvecs = np.linalg.eig(matrix_a)
print(f"Eigenvalues: {eigenvals}")
print("Eigenvectors:")
print(eigenvecs)



=== Exercise 7: Linear Algebra ===
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [14]:
try:
    inverse = np.linalg.inv(matrix_a)
    print("Matrix inverse:")
    print(inverse)
    
    # Verify: A * A^(-1) = I
    identity_check = np.dot(matrix_a, inverse)
    print("A * A^(-1) (should be identity):")
    print(identity_check)
except:
    print("Matrix is singular (no inverse)")


Matrix inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
A * A^(-1) (should be identity):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [15]:
print("\n=== Exercise 8: Statistics & Normalization ===")
# Generate sample data
np.random.seed(42)  # For reproducible results
data = np.random.normal(100, 15, 1000)  # mean=100, std=15, 1000 samples

print(f"Original data stats:")
print(f"Mean: {data.mean():.2f}")
print(f"Std: {data.std():.2f}")
print(f"Min: {data.min():.2f}")
print(f"Max: {data.max():.2f}")

# Normalize (z-score)
normalized = (data - data.mean()) / data.std()
print(f"\nNormalized data stats:")
print(f"Mean: {normalized.mean():.10f}")
print(f"Std: {normalized.std():.2f}")


=== Exercise 8: Statistics & Normalization ===
Original data stats:
Mean: 100.29
Std: 14.68
Min: 51.38
Max: 157.79

Normalized data stats:
Mean: 0.0000000000
Std: 1.00


In [16]:
print("\n=== Exercise 9: Array Manipulation ===")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

# Stacking
horizontal = np.hstack((arr1, arr2, arr3))
vertical = np.vstack((arr1, arr2, arr3))

print(f"Arrays: {arr1}, {arr2}, {arr3}")
print(f"Horizontal stack: {horizontal}")
print(f"Vertical stack:\n{vertical}")

# Advanced indexing
matrix_big = np.arange(20).reshape(4, 5)
print(f"\nBig matrix:\n{matrix_big}")
print(f"Second row: {matrix_big[1, :]}")
print(f"Third column: {matrix_big[:, 2]}")
print(f"2x2 submatrix: \n{matrix_big[1:3, 2:4]}")


=== Exercise 9: Array Manipulation ===
Arrays: [1 2 3], [4 5 6], [7 8 9]
Horizontal stack: [1 2 3 4 5 6 7 8 9]
Vertical stack:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Big matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Second row: [5 6 7 8 9]
Third column: [ 2  7 12 17]
2x2 submatrix: 
[[ 7  8]
 [12 13]]


In [17]:
print("\n=== Exercise 10: Correlation & Covariance ===")
# Generate correlated data
np.random.seed(42)
x = np.random.normal(0, 1, 100)
y = 2 * x + np.random.normal(0, 0.5, 100)  # y correlated with x
z = np.random.normal(0, 1, 100)  # z independent

data_matrix = np.vstack((x, y, z))
print("Data shape:", data_matrix.shape)

# Correlation matrix
correlation_matrix = np.corrcoef(data_matrix)
print("Correlation matrix:")
print(correlation_matrix)
# Covariance matrix
covariance_matrix = np.cov(data_matrix)
print("Covariance matrix:")
print(covariance_matrix)

print("\n🎉 ALL 10 EXERCISES COMPLETED! 🎉")
print("You've mastered NumPy fundamentals!")
print("Next: Pandas for data manipulation")



=== Exercise 10: Correlation & Covariance ===
Data shape: (3, 100)
Correlation matrix:
[[1.         0.96549437 0.19083991]
 [0.96549437 1.         0.18146912]
 [0.19083991 0.18146912 1.        ]]
Covariance matrix:
[[0.82476989 1.59046269 0.18792225]
 [1.59046269 3.29014231 0.35690504]
 [0.18792225 0.35690504 1.17566937]]

🎉 ALL 10 EXERCISES COMPLETED! 🎉
You've mastered NumPy fundamentals!
Next: Pandas for data manipulation
